# Generated by Django 5.0.6 on 2024-06-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
