# Generated by Django 5.0.6 on 2024-06-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='uploaded_materials',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
