# Generated by Django 5.0.6 on 2024-06-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trainer_uploaded_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='faiss_index',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trainer',
            name='faiss_meta',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='uploaded_materials',
            field=models.FileField(upload_to='uploads/materials/'),
        ),
    ]
