# Generated by Django 5.0.6 on 2024-06-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trainer_faiss_index_trainer_faiss_meta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='faiss_index',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='faiss_meta',
        ),
        migrations.AddField(
            model_name='trainer',
            name='faiss_index_3_small',
            field=models.FileField(blank=True, null=True, upload_to='uploads/indexes'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='faiss_meta_3_small',
            field=models.FileField(blank=True, null=True, upload_to='uploads/metadata'),
        ),
    ]
