# Generated by Django 5.0.6 on 2024-06-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_trainer_faiss_index_remove_trainer_faiss_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='uploaded_materials',
            field=models.FileField(upload_to='uploads/materials'),
        ),
    ]
