# Generated by Django 5.0.6 on 2024-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_trainer_uploaded_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='faiss_index_3_small',
            field=models.FilePathField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='faiss_meta_3_small',
            field=models.FilePathField(default=''),
            preserve_default=False,
        ),
    ]
