# Generated by Django 5.0.6 on 2024-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_trainer_faiss_index_3_small_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='faiss_index_3_small',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='faiss_meta_3_small',
            field=models.FilePathField(null=True),
        ),
    ]
