# Generated by Django 5.0.6 on 2024-06-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_trainer_faiss_index_3_small_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='faiss_index_3_small',
            field=models.FileField(null=True, upload_to='uploads/indexes'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='faiss_meta_3_small',
            field=models.FileField(null=True, upload_to='uploads/metadata'),
        ),
    ]
